<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901154912 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campaign (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, template_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1512DD9033212A ON campaign (tenant_id)');
        $this->addSql('CREATE INDEX IDX_1F1512DD5DA0FB8 ON campaign (template_id)');
        $this->addSql('CREATE TABLE campaign_contact_list (campaign_id INT NOT NULL, contact_list_id INT NOT NULL, PRIMARY KEY (campaign_id, contact_list_id))');
        $this->addSql('CREATE INDEX IDX_3187ABD9F639F774 ON campaign_contact_list (campaign_id)');
        $this->addSql('CREATE INDEX IDX_3187ABD9A781370A ON campaign_contact_list (contact_list_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(12) NOT NULL, name VARCHAR(50) NOT NULL, tags JSON DEFAULT NULL, opt_in BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E6389033212A ON contact (tenant_id)');
        $this->addSql('CREATE TABLE contact_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contact_list_contact (contact_list_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (contact_list_id, contact_id))');
        $this->addSql('CREATE INDEX IDX_BC9A0901A781370A ON contact_list_contact (contact_list_id)');
        $this->addSql('CREATE INDEX IDX_BC9A0901E7A1254A ON contact_list_contact (contact_id)');
        $this->addSql('CREATE TABLE message_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, wa_message_id VARCHAR(255) DEFAULT NULL, error_message TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, campaign_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A60AE2299033212A ON message_log (tenant_id)');
        $this->addSql('CREATE INDEX IDX_A60AE229F639F774 ON message_log (campaign_id)');
        $this->addSql('CREATE INDEX IDX_A60AE229E7A1254A ON message_log (contact_id)');
        $this->addSql('CREATE UNIQUE INDEX campaign_contact_unique ON message_log (campaign_id, contact_id)');
        $this->addSql('CREATE TABLE message_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, meta_template_name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, language VARCHAR(10) NOT NULL, body_text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9E46DB929033212A ON message_template (tenant_id)');
        $this->addSql('CREATE TABLE tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, plan VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE whats_app_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, waba_id VARCHAR(255) NOT NULL, phone_number_id VARCHAR(255) NOT NULL, access_token TEXT NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7DA0412A9033212A ON whats_app_account (tenant_id)');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD5DA0FB8 FOREIGN KEY (template_id) REFERENCES message_template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_contact_list ADD CONSTRAINT FK_3187ABD9F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE campaign_contact_list ADD CONSTRAINT FK_3187ABD9A781370A FOREIGN KEY (contact_list_id) REFERENCES contact_list (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6389033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact_list_contact ADD CONSTRAINT FK_BC9A0901A781370A FOREIGN KEY (contact_list_id) REFERENCES contact_list (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_list_contact ADD CONSTRAINT FK_BC9A0901E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_log ADD CONSTRAINT FK_A60AE2299033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_log ADD CONSTRAINT FK_A60AE229F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_log ADD CONSTRAINT FK_A60AE229E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB929033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE whats_app_account ADD CONSTRAINT FK_7DA0412A9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_1F1512DD9033212A');
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_1F1512DD5DA0FB8');
        $this->addSql('ALTER TABLE campaign_contact_list DROP CONSTRAINT FK_3187ABD9F639F774');
        $this->addSql('ALTER TABLE campaign_contact_list DROP CONSTRAINT FK_3187ABD9A781370A');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6389033212A');
        $this->addSql('ALTER TABLE contact_list_contact DROP CONSTRAINT FK_BC9A0901A781370A');
        $this->addSql('ALTER TABLE contact_list_contact DROP CONSTRAINT FK_BC9A0901E7A1254A');
        $this->addSql('ALTER TABLE message_log DROP CONSTRAINT FK_A60AE2299033212A');
        $this->addSql('ALTER TABLE message_log DROP CONSTRAINT FK_A60AE229F639F774');
        $this->addSql('ALTER TABLE message_log DROP CONSTRAINT FK_A60AE229E7A1254A');
        $this->addSql('ALTER TABLE message_template DROP CONSTRAINT FK_9E46DB929033212A');
        $this->addSql('ALTER TABLE whats_app_account DROP CONSTRAINT FK_7DA0412A9033212A');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('DROP TABLE campaign_contact_list');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contact_list');
        $this->addSql('DROP TABLE contact_list_contact');
        $this->addSql('DROP TABLE message_log');
        $this->addSql('DROP TABLE message_template');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE whats_app_account');
    }
}
